spring.application.name=demo

# ── PostgreSQL ────────────────────────────────────────────────────────────────
spring.datasource.url=jdbc:postgresql://postgres:5432/prova_db
spring.datasource.username=admin
spring.datasource.password=agape123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.default_schema=cliente_schema

spring.jpa.hibernate.ddl-auto=none

# ── JPA / Hibernate ───────────────────────────────────────────────────────────
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=cliente_schema
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ✅ Força criação do schema antes do Hibernate inicializar
spring.jpa.properties.javax.persistence.schema-generation.create-source=metadata
spring.sql.init.mode=always

# ── Swagger ───────────────────────────────────────────────────────────────────
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.filter=true